diff --git a/Makefile b/Makefile
index 1ae4b05..5be420c 100644
--- a/Makefile
+++ b/Makefile
@@ -134,7 +134,7 @@ DEPENDS+=$(BOSSASH_SRCS:%.cpp=$(OBJDIR)/%.d)
 # Tools
 #
 #Q=@
-CXX=g++
+CXX?=g++
 ARM=arm-none-eabi-
 ARMAS=$(ARM)as
 ARMOBJCOPY=$(ARM)objcopy
@@ -250,7 +250,7 @@ $(foreach bmp,$(BOSSA_BMPS),$(eval $(call bossa_bmp,$(bmp))))
 $(OBJDIR):
 	@mkdir $@
     
-$(OBJDIR)/arm-dis:
+$(OBJDIR)/arm-dis: $(OBJDIR)
 	@mkdir $@
     
 $(BINDIR):
